# Generated by Django 5.1.6 on 2025-02-28 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NewsItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(verbose_name="Заголовок")),
                ("content", models.CharField(verbose_name="Описание")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images/",
                        verbose_name="Изображение",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True, verbose_name="Дата")),
            ],
            options={
                "verbose_name": "Новости",
                "verbose_name_plural": "Новости",
                "ordering": ["-date"],
            },
        ),
    ]
